### ISSUE TITLE
Major update tracker

### ISSUE THREAD

**Issue by thinkjrs** [thinkjrs/stevens-services#1]
This tracks major items related to the next release of stevens-services.com.

In particular,

- [x] deployment engineering,
- [x] content engineering (sanity),
- [x] content completion,
- [x] content review, 
- [x] basic design implementation,
- [x] basic checkout process.
